services:
  auth:
    build:
      context: ./services/auth
      dockerfile: Dockerfile
    ports:
      - "3001:8000"
    volumes:
      - ./services/auth:/app
      - ./db:/app/db
      - ./services:/app/services
    env_file:
      - ./services/auth/.env
    # Removing the incorrect environment variable to allow fallback to file
    restart: unless-stopped

  api:
    build:
      context: ./services/api
      dockerfile: dockerfile
    ports:
      - "3002:8001"
    volumes:
      - ./services/api:/app
      - ./db:/app/db
      - ./services:/app/services
    env_file:
      - ./services/api/.env
    depends_on:
      - auth
    restart: unless-stopped

  llm:
    build:
      context: ./services/llm
      dockerfile: Dockerfile
    ports:
      - "3003:8002"
    volumes:
      - ./services/llm:/app
      - ./db:/app/db
      - ./services:/app/services
    env_file:
      - ./services/llm/src/.env
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - api
    restart: unless-stopped

  crew:
    build:
      context: ./services/crew
      dockerfile: Dockerfile
    ports:
      - "3004:8003"
    volumes:
      - ./services/crew:/app
      - ./db:/app/db
      - ./services:/app/services
    env_file:
      - ./services/crew/.env
    # Removing the incorrect environment variable to allow fallback to file
    depends_on:
      - api
    restart: unless-stopped

volumes:
  db:
  services: