[build]
  command = "cd packages/student-portal && npm install --no-workspaces --legacy-peer-deps && npm run build"
  publish = "packages/student-portal/dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20.10.0"
  NPM_FLAGS = "--workspaces"
  NPM_UPDATE = "true"
  NODE_ENV = "production"
  VITE_APP_ENV = "production"
  VITE_BASE = "/"
  
  # Build environment
  CI = "false"
  SKIP_PREFLIGHT_CHECK = "true"
  TSC_COMPILE_ON_ERROR = "true"

[dev]
  framework = "vite"
  target = "packages/student-portal"
  port = 5173

# Redirect all requests to index.html for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200