matching_task:
  description: >
    Review the filtered list of colleges returned by the Firestore tool by inputing GPA: {student_GPA}, SAT: {student_sat}, ACT: {student_act}. If any field is None then ignore it. Use your own reasoning and knowledge of admissions to re-evaluate the results based on the student's profile GPA: {student_GPA}, SAT: {student_sat}, ACT: {student_act}, Interests: {student_interests}. Refine the list to include up to 20 institutions where the student is most likely to be a good fit. If fewer than 20 colleges are available from the initial filtered list, include them all.
  expected_output: >
    A refined, prioritized python list of up to 20 recommended colleges based on deeper analysis of the filtered set, aligned with the student's academic performance.
  agent: student_data_matcher

reporting_task:
  description: >
    Using the refined college list and the student's academic interests {student_interests}, compile a detailed college application recommendation report. Clearly outline the top 10 colleges the student should consider applying to, with specific justifications for each recommendation based on fit, competitiveness, and alignment with the student's goals.
  expected_output: >
    A JSON-formatted recommendation report containing the top 10 colleges, where each college entry includes the name and reason for recommendation.
  agent: college_admission_advisor

roadmap_task:
  description: >
    Generate a personalized college application roadmap for a student based on their profile and target schools.
    
    INPUTS:
    - User ID: {user_id} - Use this exact ID to identify the student
    - Target Schools: {target_schools} - List of colleges the student is applying to
    - Student Profile Data: Academic information (GPA, grade level, test scores), interests, and preferences
    
    CONSIDERATIONS:
    - Application deadlines for each target school
    - Student's current academic standing and test preparation needs
    - Balance between common tasks (applicable to all schools) and school-specific tasks
    - Progressive scheduling that distributes work evenly and prioritizes earlier deadlines
    - Student's interests and study style preferences when making recommendations
    - Assign appropriate priority levels (high/medium/low) to tasks based on urgency and importance
    
    RECOMMENDATION PRIORITIES:
    Assign priorities to recommendations based on these factors:
    - HIGH priority: Critical actions needed immediately (low GPA for target schools, missing required tests, approaching deadlines)
    - MEDIUM priority: Important actions that will significantly improve chances (extracurricular enhancements, essay preparation)
    - LOW priority: Helpful suggestions that would be beneficial but not critical
    
    The FirestoreRoadmapTool will handle fetching any additional data needed and updating the database.
    Do not attempt to use hardcoded or sample user IDs.
  expected_output: >
    A JSON object containing:
    1. A list of tasks, where each task includes EXACTLY these field names:
       - "id": A unique identifier (can be a string like "task_1")
       - "title": A concise task title
       - "description": A detailed description of what needs to be done
       - "dueDate": In YYYY-MM-DD format
       - "category": One of "Application", "Test Prep", "Essay", "Financial Aid", "Research"
       - "priority": One of "high", "medium", "low"
       - "school": The specific school or "All Schools" if applicable to all
    
    2. A list of recommendations, where each recommendation includes EXACTLY these field names:
       - "text": The recommendation content
       - "priority": One of "high", "medium", "low"
    
    Example format:
    {
      "tasks": [
        {
          "id": "task_1",
          "title": "Complete SAT Preparation",
          "description": "Study for the SAT using practice tests and review materials",
          "dueDate": "2025-05-15",
          "category": "Test Prep",
          "priority": "high",
          "school": "All Schools"
        }
      ],
      "recommendations": [
        {
          "text": "Join academic clubs to enhance your extracurricular profile",
          "priority": "medium"
        }
      ]
    }
    
    Tasks should be logically sequenced with earlier deadlines for preparation activities
    and appropriate spacing to avoid overwhelming the student.
  agent: "roadmap_generator"
  max_retries: 3
  retry_on_fail: true