matching_task:
  description: >
    Review the filtered list of colleges returned by the Firestore tool by inputing GPA: {student_GPA}, SAT: {student_sat}, ACT: {student_act}. If any field is None then ignore it. Use your own reasoning and knowledge of admissions to re-evaluate the results based on the student's profile GPA: {student_GPA}, SAT: {student_sat}, ACT: {student_act}, Interests: {student_interests}. Refine the list to include up to 20 institutions where the student is most likely to be a good fit. If fewer than 20 colleges are available from the initial filtered list, include them all.
  expected_output: >
    A refined, prioritized python list of up to 20 recommended colleges based on deeper analysis of the filtered set, aligned with the student's academic performance.
  agent: student_data_matcher

reporting_task:
  description: >
    Using the refined college list and the student's academic interests {student_interests}, compile a detailed college application recommendation report. Clearly outline the top 10 colleges the student should consider applying to, with specific justifications for each recommendation based on fit, competitiveness, and alignment with the student's goals.
  expected_output: >
    A Python list of recommendation report objects containing the top 10 colleges, where each college entry includes the name and reason for recommendation.
    Example format:
    [
      {
        "College_Name": "College A",
        "Reason": "Reason for recommendation"
      },
      {
        "College_Name": "College B",
        "Reason": "Reason for recommendation"
      },
      ...
    ]
  agent: college_admission_advisor

roadmap_task:
  description: >
    Generate a personalized college application roadmap for a student based on their profile and target schools.
    
    INPUTS:
    - User ID: {user_id} - Use this exact ID to identify the student
    - Target Schools: {target_schools} - List of colleges the student is applying to
    - Student Profile Data: Academic information (GPA, grade level, test scores), interests, and preferences
    
    CONSIDERATIONS:
    - Application deadlines for each target school
    - Student's current academic standing and test preparation needs
    - Balance between common tasks (applicable to all schools) and school-specific tasks
    - Progressive scheduling that distributes work evenly and prioritizes earlier deadlines
    - Student's interests and study style preferences when making recommendations
    - Assign appropriate priority levels (high/medium/low) to tasks based on urgency and importance
    
    IMPORTANT: ONLY USE THESE EXACT TASK CATEGORIES:
    1. "Test Prep" - For all test-related tasks (SAT/ACT registration, preparation, etc.)
    2. "Application" - For application forms, submission deadlines, and recommendation letters
    3. "Financial Aid" - For FAFSA, scholarships, and financial aid applications
    4. "Essay" - For personal statements and school-specific essays
    5. "Research" - For school research, program investigation, and campus visits
    6. "Extracurricular" - For activities to enhance application profile
    
    RECOMMENDATION PRIORITIES:
    Assign priorities to recommendations based on these factors:
    - HIGH priority: Critical actions needed immediately (low GPA for target schools, missing required tests, approaching deadlines)
    - MEDIUM priority: Important actions that will significantly improve chances (extracurricular enhancements, essay preparation)
    - LOW priority: Helpful suggestions that would be beneficial but not critical
    
    The FirestoreRoadmapTool will handle fetching any additional data needed and updating the database.
    Do not attempt to use hardcoded or sample user IDs.
  expected_output: >
    A JSON object containing:
    1. A list of tasks, where each task includes EXACTLY these field names:
       - "id": A unique identifier (can be a string like "task_1")
       - "title": A concise task title
       - "description": A detailed description of what needs to be done
       - "dueDate": In YYYY-MM-DD format
       - "category": MUST be one of ONLY these six: "Test Prep", "Application", "Financial Aid", "Essay", "Research", "Extracurricular"
       - "priority": One of "high", "medium", "low"
       - "school": The specific school or "All Schools" if applicable to all
    
    2. A list of recommendations, where each recommendation includes EXACTLY these field names:
       - "text": The recommendation content
       - "priority": One of "high", "medium", "low"
    
    Example format:
    {
      "tasks": [
        {
          "id": "task_1",
          "title": "Register for SAT/ACT",
          "description": "Register for upcoming SAT or ACT test dates based on your preferred test prep method.",
          "dueDate": "2025-03-15",
          "category": "Test Prep",
          "priority": "high",
          "school": "All Schools"
        },
        {
          "id": "task_2",
          "title": "Complete SAT/ACT Preparation",
          "description": "Study for the SAT/ACT using practice tests and review materials aligned with your visual learning style.",
          "dueDate": "2025-05-15",
          "category": "Test Prep",
          "priority": "high",
          "school": "All Schools"
        },
        {
          "id": "task_3",
          "title": "Draft Personal Statement",
          "description": "Write your common application personal statement focusing on your academic interests and experiences.",
          "dueDate": "2025-07-30",
          "category": "Essay",
          "priority": "high",
          "school": "All Schools"
        },
        {
          "id": "task_4",
          "title": "Research UCLA Programs",
          "description": "Research specific programs at UCLA that align with your STEM interests to mention in your application.",
          "dueDate": "2025-08-15",
          "category": "Research",
          "priority": "medium",
          "school": "UCLA"
        },
        {
          "id": "task_5",
          "title": "Complete UCLA Supplemental Essays",
          "description": "Write the UCLA-specific essays focusing on your academic achievements and interests.",
          "dueDate": "2025-10-15",
          "category": "Essay",
          "priority": "high",
          "school": "UCLA"
        },
        {
          "id": "task_6",
          "title": "Submit FAFSA Application",
          "description": "Complete and submit the Free Application for Federal Student Aid (FAFSA) for financial assistance.",
          "dueDate": "2025-10-01",
          "category": "Financial Aid",
          "priority": "high",
          "school": "All Schools"
        },
        {
          "id": "task_7",
          "title": "Request Letters of Recommendation",
          "description": "Ask teachers who know your academic abilities well to write recommendation letters for your applications.",
          "dueDate": "2025-09-01",
          "category": "Application",
          "priority": "high",
          "school": "All Schools"
        },
        {
          "id": "task_8",
          "title": "Submit UCLA Application",
          "description": "Complete and submit your UCLA application before the deadline, ensuring all required materials are included.",
          "dueDate": "2025-11-30",
          "category": "Application",
          "priority": "high",
          "school": "UCLA"
        },
        {
          "id": "task_9",
          "title": "Join Academic Club",
          "description": "Participate in a STEM-related academic club to enhance your extracurricular profile.",
          "dueDate": "2025-04-30",
          "category": "Extracurricular",
          "priority": "medium",
          "school": "All Schools"
        }
      ],
      "recommendations": [
        {
          "text": "Join academic clubs related to STEM to enhance your extracurricular profile",
          "priority": "medium"
        },
        {
          "text": "Schedule a campus visit to UCLA if possible to demonstrate interest",
          "priority": "low"
        },
        {
          "text": "Create a calendar system to track all application deadlines",
          "priority": "high"
        }
      ]
    }
    
    Tasks should be logically sequenced with earlier deadlines for preparation activities
    and appropriate spacing to avoid overwhelming the student. Always include application submission tasks for each target school.
  agent: "roadmap_generator"
  max_retries: 3
  retry_on_fail: true